// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqxqksedyhsicgfufayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxeHFrc2VkeWhzaWNnZnVmYXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTg5ODcsImV4cCI6MjA2NzM3NDk4N30.UFc9HRMYNYioUjPxRD9PmTxI0-N9XXwcCcX1t1uHJFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});